runner:
  class_name: OnPolicyRunner

  # General
  num_steps_per_env: 24 # Number of steps per environment per iteration
  max_iterations: 1500 # Number of policy updates
  seed: 1

  # Observations
  obs_groups:
    actor:
      - policy
    critic:
      - policy
      - privileged
    rnd_state:
      - policy

  # Logging
  logger: tensorboard
  save_interval: 50 # Check for potential saves every `save_interval` iterations
  experiment_name: spider-bot
  run_name: ""

  # Actor
  actor:
    class_name: MLPModel
    hidden_dims: [1024, 512, 256]
    activation: elu
    obs_normalization: false
    stochastic: true
    init_noise_std: 1.0
    noise_std_type: "scalar" # 'scalar' or 'log'
    state_dependent_std: false

  # Critic
  critic:
    class_name: MLPModel
    hidden_dims: [1024, 512, 256]
    activation: elu
    obs_normalization: false
    stochastic: false

  # Algorithm
  algorithm:
    class_name: PPO

    # Training
    optimizer: adam # adam, adamw, sgd, rmsprop
    learning_rate: 0.001
    num_learning_epochs: 5
    num_mini_batches: 4 # mini batch size = num_envs * num_steps / num_mini_batches
    schedule: adaptive # adaptive, fixed
    normalize_advantage_per_mini_batch: false

    # Value function
    value_loss_coef: 1.0
    clip_param: 0.2
    use_clipped_value_loss: true

    # Surrogate loss
    desired_kl: 0.01
    entropy_coef: 0.01
    gamma: 0.99
    lam: 0.95
    max_grad_norm: 1.0

    # Random network distillation
    rnd_cfg:
      weight: 0.0 # Initial weight of the RND reward
      weight_schedule: null # This is a dictionary with a required key called "mode". Please check the RND module for more information
      reward_normalization: false # Whether to normalize RND reward
      learning_rate: 0.001 # Learning rate for RND
      num_outputs: 1 # Number of outputs of RND network. Note: if -1, then the network will use dimensions of the observation
      predictor_hidden_dims: [-1] # Hidden dimensions of predictor network
      target_hidden_dims: [-1] # Hidden dimensions of target network
